# Generated by Django 4.1.5 on 2023-01-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("b4", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photos",
            name="background_photo",
            field=models.ImageField(upload_to="background"),
        ),
        migrations.AlterField(
            model_name="photos",
            name="converte_photo",
            field=models.ImageField(upload_to="converte"),
        ),
        migrations.AlterField(
            model_name="photos",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="photos",
            name="origin_photo",
            field=models.ImageField(null=True, upload_to="origin"),
        ),
    ]
