# Generated by Django 4.0.3 on 2023-01-12 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b4', '0003_alter_test_origin_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
