# Generated by Django 4.0.3 on 2023-01-12 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b4', '0005_binarydata_delete_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='binarydata',
            old_name='binary_data',
            new_name='data',
        ),
    ]
