# Generated by Django 4.0.3 on 2023-01-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b4', '0007_test_delete_binarydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinaryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.BinaryField()),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
