# Generated by Django 4.0.3 on 2023-01-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b4', '0008_binarydata_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_phto', models.ImageField(null=True, upload_to='origin')),
            ],
        ),
        migrations.DeleteModel(
            name='BinaryData',
        ),
    ]
