# Generated by Django 4.0.3 on 2023-01-12 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b4', '0009_test_delete_binarydata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='origin_phto',
            new_name='origin_photo',
        ),
    ]
