# Generated by Django 4.1.5 on 2023-01-12 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("b4", "0002_alter_photos_background_photo_and_more"),
        ("b4", "0010_rename_origin_phto_test_origin_photo"),
    ]

    operations = []
