# Generated by Django 4.0.3 on 2023-01-13 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b4', '0010_rename_origin_phto_test_origin_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
