# Generated by Django 4.0.3 on 2023-01-14 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b4', '0012_canvasimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CanvasImage',
        ),
    ]
