# Generated by Django 4.0.3 on 2023-01-15 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b4', '0013_delete_canvasimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='origin')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
