# Generated by Django 4.1.5 on 2023-01-16 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("b4", "0011_merge_20230112_1749"),
        ("b4", "0014_cameraimage"),
    ]

    operations = []
