# Generated by Django 4.0.3 on 2023-01-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b4', '0014_cameraimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameraimage',
            name='image',
            field=models.ImageField(upload_to='origin_blob'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='background_color',
            field=models.CharField(default='#ffffff', max_length=10),
        ),
    ]
