# Generated by Django 4.0.3 on 2023-01-29 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b4', '0015_alter_cameraimage_image_and_more'),
        ('b4', '0019_alter_photos_background_color'),
    ]

    operations = [
    ]
