# Generated by Django 3.2 on 2023-01-31 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b4', '0021_auto_20230131_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='converte_photo',
        ),
        migrations.AddField(
            model_name='photos',
            name='converted_photo',
            field=models.ImageField(null=True, upload_to='converted'),
        ),
    ]
