# Generated by Django 3.2 on 2023-02-23 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b4', '0022_auto_20230201_0022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CameraImage',
        ),
    ]
